from __future__ import annotations

from .base import LLMClient


class MockClient(LLMClient):
    """Simple offline client so the project can be tested without paid APIs."""

    def generate(self, prompt: str) -> str:
        prompt_lower = prompt.lower()

        if "berlin wall" in prompt_lower:
            answer = "The Berlin Wall fell in 1989."
        elif "declaration of independence" in prompt_lower:
            answer = "Thomas Jefferson was the principal drafter of the Declaration of Independence."
        elif "consumer price index" in prompt_lower:
            answer = "The Consumer Price Index measures changes over time in prices paid for a basket of goods and services."
        elif "opportunity cost" in prompt_lower:
            answer = "Opportunity cost is the value of the next best alternative you give up when making a choice."
        elif "stock dividend" in prompt_lower:
            answer = "A stock dividend is a dividend paid in additional shares rather than cash."
        elif "sec" in prompt_lower and "financial markets" in prompt_lower:
            answer = "The SEC regulates securities markets, enforces securities laws, and helps protect investors."
        else:
            answer = "This is a mock response for testing the project pipeline without a live API."

        if "final answer:" in prompt_lower or "reason step by step" in prompt_lower:
            return (
                "Reasoning: This response was generated by the offline mock client for testing.\n"
                f"Final Answer: {answer}"
            )

        return answer
